- name: Demo on the Variables
  hosts: all
  #vars_files:
  #  - example-vars.yml
  vars:
    URL: play.example.com
    PROJECT: example
  vars_prompt:
    - name: URL
      prompt: Enter URL
      private: no
  
  tasks:
    - name: Print URL
      debug: 
        msg: URL = {{ URL }}
    - name: print URL from  tasks
      debug:
        msg: URL = {{ URL }}
      vars:
       URL: task.example.com 

#Variable precedences(High Priority)
# command line vars with -e
# Tasks
# vars_files
# vars_prompt
# vars
# inventory vars

- name: Demo on dynamic variables
  hosts: all
  tasks:

    - name: Gathering Todays Date
      shell: date +%F
      register: out

    - name: Print Date
      debug:
        msg: Date = {{ out.stdout }}

    - name: Set a fact
      set_fact:
        DATE: "{{ out.stdout }}"

    - name: Print DATE
      debug:
        msg: DATE = {{DATE}}