- name: Demo on the Variables
  hosts: all
  vars_files:
    - example-vars.yml
  vars:
    URL: play.example.com
    PROJECT: example
  
  tasks:
    - name: Print URL
      debug: 
        msg: URL = {{ URL }}
    - name: print URL from  tasks
      debug:
        msg: URL = {{ URL }}
      vars:
       URL: task.example.com 

#Variable precedences
# Tasks
# vars-files
# vars