- name: Demo on the Variables
  hosts: all
  #vars_files:
  #  - example-vars.yml
  vars:
    URL: play.example.com
    PROJECT: example
  vars_prompt:
    - name: URL
      prompt: Enter URL
      private: no
  
  tasks:
    - name: Print URL
      debug: 
        msg: URL = {{ URL }}
    - name: print URL from  tasks
      debug:
        msg: URL = {{ URL }}
      vars:
       URL: task.example.com 

#Variable precedences(High Priority)
# Tasks
# vars_files
# vars_prompt
# vars