- name: Demo on Conditions
  hosts: all
  tasks:
    - name: Print CentOS
      debug:
        msg: Hello Zelarsoft_Centos
      when: OS == "CentOS"

    - name: Print Ubuntu
      debug:
        msg: Hello Sree
      when: OS == "Ubuntu"