- name: SetUp TODOS APP Project
  hosts: all
  become: yes
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        update_cache: yes
        state: present
    
    - name: Start Nginx
      systemd:
        state: started
        name: nginx
        enabled: yes