- name: Install dependencies
  apt:
    name: npm
    update_cache: yes
    state: present

- name: Download Frontend from Nexus
  get_url:
    url: http://172.31.7.112:8081/repository/todo/todo-{{APP_VERSION}}.zip
    dest: /tmp/todo-0.0.13.zip
    username: admin
    password: admin123

- name: create Directory
  file:
    path: /home/todo
    state: directory

- name: Unzip the Downloaded Content
  unarchive:
     src: /tmp/todo-0.0.13.zip
     dest: /home/todo
     remote_src: yes

- name: Copy todo Service file
  copy:
    src: todo.service
    dest: /etc/systemd/system/todo.service

- name: Start TODO Service
  systemd:
    name: "todo"
    daemon_reload: yes
    state: started
    enabled: yes