    - name: Install Dependencies
      apt:
        name: "{{packages}}"
        update_cache: yes
        state: present

    # - name: Download Artifacts from Nexus
    #   get_url:
    #     url: http://172.31.7.112:8081/repository/frontend/frontend-{{APP_VERSION}}.zip
    #     dest: /tmp
    #     username: admin 
    #     password: admin123

    - name: Import Download Nexus Artifacrs from Common role
      include_role:
       name: common
       tasks_from: download-nexus-Artifacts.yml

    # - name: Create Frontend Directory
    #   file:
    #     path: /var/www/html/frontend
    #     state: directory

    # - name: Unzip the Downloaded Content
    #   unarchive:
    #       src: /tmp/{{COMPONENT}}.zip
    #       dest: /var/www/html/frontend
    #       remote_src: yes

    - name: Replace content
      replace:
        path: /etc/nginx/sites-enabled/default
        regexp: root /var/www/html;
        replace: root /root/dist;
    
  
    - name: Start Nginx
      systemd:
        state: restarted
        name: nginx
        enabled: yes   
        
    - name: Replace content
      replace:
        path: /root/config/index.js
        regexp: '127.0.0.2'
        replace: 'login.sree-cloud-devops.online'

    - name: Replace content
      replace:
        path: /root/config/index.js
        regexp: '127.0.0.3'
        replace: 'todo.sree-cloud-devops.online'

    
    - name: Use NPM to start 
      command: npm start
      args:
        chdir: /root
      async: 42
      poll: 0
      become: yes
      become_user: root

    
    # - name: To start NPM Service
    #   template:
    #     src: npmstart.service
    #     dest: /var/www/html/frontend
      #notify: Restart Nginx

    # - name: To start npm
    #   shell: npm start
    #   args:
    #    chdir: /var/www/html/frontend
