    - name: Install Dependencies
      apt:
        name: "{{packages}}"
        update_cache: yes
        state: present

#    - name: Download Artifacts from Nexus
#      get_url:
#        url: http://172.31.7.112:8081/repository/frontend/frontend-{{APP_VERSION}}.zip
#        dest: /tmp/{{COMPONENT}}.zip
#        username: admin
#        password: admin123
#
    - name: Import Download Nexus Artifacrs from Common role
      include_role:
        name: common
        tasks_from: download-nexus-Artifacts.yml

    - name: Remove default files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/nginx/sites-enabled/default
        - /etc/nginx/sites-available/default

    - name: Copy config file from templates
      template:
        src: todo.config
        dest: /etc/nginx/sites-enabled/todo.config
      notify: Restart Nginx

    - name: Start Nginx
      systemd:
        state: started
        name: nginx
        enabled: yes



    - name: Install Node Exporter Premetheus Monitoring from common role
      include_role:
          name: common
          tasks_from: node_exporter.yml

#    - name: To start NPM Service
#      template:
#         src: npmstart.service
#         dest: /root



    - name: Use NPM to start
      command: npm start
      args:
        chdir: /root
      async: 42
      poll: 0
      become: yes
      become_user: root

#
#    - name: Create Frontend Directory
#      file:
#        path: /var/www/html/frontend
#        state: directory
#
#    - name: Unzip the Downloaded Content
#      unarchive:
#          src: /tmp/{{COMPONENT}}.zip
#          dest: /var/www/html/frontend
#          remote_src: yes
#
#    - name: Replace content
#      replace:
#        path: /etc/nginx/sites-enabled/default
#        regexp: root /var/www/html;
#        replace: root /var/www/html/frontend/dist;
#
#
#
#    - name: Update Index.js file Config
#      template:
#        src: index.js
#        dest: /var/www/html/frontend/config/index.js

#    - name: Start Nginx
#      systemd:
#        state: restarted
#        name: nginx
#        enabled: yes
#
#
#    - name: Use NPM to start
#      command: npm start
#      args:
#        chdir: /var/www/html/frontend
#      async: 42
#      poll: 0
#      become: yes
#      become_user: root

    
#

    # - name: To start npm
    #   shell: npm start
    #   args:
    #    chdir: /var/www/html/frontend

    #checking swwwwwww  llllll 22999 ewn
    # 17-06-2021 intelj using
