    - name: Install Dependencies
      apt:
        name: "{{packages}}"
        update_cache: yes
        state: present

    - name: Download Artifacts from Nexus
      get_url:
        url: http://172.31.7.112:8081/repository/frontend/frontend-{{APP_VERSION}}.zip
        dest: /tmp/{{COMPONENT}}.zip
        username: admin
        password: admin123


    - name: Create Frontend Directory
      file:
        path: /var/www/html/frontend
        state: directory

    - name: Unzip the Downloaded Content
      unarchive:
          src: /tmp/{{COMPONENT}}.zip
          dest: /var/www/html/frontend
          remote_src: yes

    # - name: Replace content
    #   replace:
    #     path: /etc/nginx/sites-enabled/default
    #     regexp: root /var/www/html;
    #     replace: root /var/www/html/frontend/dist;
    #   notify: Restart Nginx

    - name: Install Node Exporter Premetheus Monitoring from common role
      include_role:
          name: common
          tasks_from: node_exporter.yml


    # - name: Install Filebeat Monitoring
    #   include_role:
    #     name: common
    #     tasks_from: filebeat
    #   vars:
    #    IS_STRUCTURED: false
    #    LOG_FILES:
    #      - { file: "/var/log/nginx/access.log", type: "nginx_access" }
    #      - { file: "/var/log/nginx/error.log", type: "nginx_error" }
    
      
    - name: Copy systemd frontend npm start Service file
      template:
         src: npmstart.service
         dest: /etc/systemd/system/npmstart.service
         owner: root
         group: root

    - name: Start npm  Service
      systemd:
        name: npmstart.service
        daemon_reload: yes
        state: restarted
        enabled: yes






































# - name: Update Index.js file Config
    #   template:
    #     src: index.js
    #     dest: /var/www/html/frontend/config/index.js

    # - name: Start Nginx
    #   systemd:
    #     state: restarted
    #     name: nginx
    #     enabled: yes








    







#    - name: Start Nginx
#      systemd:
#        state: started
#        name: nginx
#        enabled: yes



    # - name: To start npm
    #   shell: npm start
    #   args:
    #    chdir: /var/www/html/frontend

    #checking swwwwwww  llllll 22999 ewn
    # 17-06-2021 intelj using

    # name: Import Download Nexus Artifacrs from Common role
      #      include_role:
      #        name: common
      #        tasks_from: download-nexus-Artifacts.yml
      #
      #    - name: Remove default files
      #      file:
      #        path: "{{ item }}"
      #        state: absent
      #      loop:
      #        - /etc/nginx/sites-enabled/default
      #        - /etc/nginx/sites-available/default
      #
      #    - name: Copy config file from templates
      #      template:
      #        src: todo.config
      #        dest: /etc/nginx/sites-enabled/todo.config
      #      notify: Restart Nginx
