    - name: Install Dependencies
      apt:
        name: "{{packages}}"
        update_cache: yes
        state: present

    - name: Download Artifacts from Nexus
      get_url:
        url: http://172.31.7.112:8081/repository/frontend/frontend-{{APP_VERSION}}.zip
        dest: /tmp
        username: admin 
        password: admin123

    - name: Create Frontend Directory
      file:
        path: /var/www/html/frontend
        state: directory

    - name: Unzip the Downloaded Content
      unarchive:
          src: /tmp/frontend-0.0.11.zip
          dest: /var/www/html/frontend
          remote_src: yes

    - name: Replace content
      replace:
        path: /etc/nginx/sites-enabled/default
        regexp: '/var/www/html/frontend/dist/frontend/dist'
        replace: '/var/www/html/frontend/dist'
    
  
    - name: Start Nginx
      systemd:
        state: restarted
        name: nginx
        enabled: yes   
        
    - name: Replace content
      replace:
        path: /var/www/html/frontend/config/index.js
        regexp: '127.0.0.2'
        replace: 'login.sree-cloud-devops.online'

    - name: Replace content
      replace:
        path: /var/www/html/frontend/config/index.js
        regexp: '127.0.0.3'
        replace: 'todo.sree-cloud-devops.online'

    - name: To start npm
      shell: npm start
      args:
       chdir: /var/www/html/frontend
