- name: Install dependencies
  apt:
    name: golang
    update_cache: yes
    state: present
- name: Download Frontend from Nexus
  git:
    repo: 'http://172.31.11.166:8081/repository/frontend/frontend-{{APP_VERSION}}.zip'
    dest: /home/ubuntu/login
    #- name: Unzip the Downloaded Content
    # unarchive:
    #  src: /root/login
    #  dest: /root/login
    # remote_src: yes

- name: Copy login Service file
  ansible.builtin.copy:
    src: /home/ubuntu/login/login.service
    dest: /etc/systemd/system/login.service
    remote_src: yes

- name: Start login Service
  systemd:
    name: "login"
    daemon_reload: yes
    state: started
    enabled: yes