- name: update Cache
  apt:
    update_cache: yes

#- name: create Directory
  #file:
    #path: /home/ubuntu
    #state: directory

- name: download golang tar 
  get_url:
      url: https://golang.org/dl/go1.15.5.linux-amd64.tar.gz
      dest: /tmp
      
 
- name: Extract the Go tarball
  unarchive:
      src: /tmp/go1.15.5.linux-amd64.tar.gz
      dest: /usr/local
      remote_src: yes


- name: Download Login from Nexus
  get_url:
    url: http://172.31.7.112:8081/repository/login/login-{{APP_VERSION}}.zip
    dest: /tmp/
    username: admin
    password: admin123

- name: Unzip the Downloaded Content
  unarchive:
     src: /tmp/login-0.0.13.zip
     dest: /home/ubuntu
     remote_src: yes


- name: copy Template {{COMPONENT}} Service file
  template:
    src: "{{COMPONENT}}.service"
    dest: /etc/systemd/system/{{COMPONENT}}.service
    

- name: Start {{COMPONENT}} Service
  systemd:
    name: "{{COMPONENT}}"
    daemon_reload: yes
    state: started
    enabled: yes