- name: Download {{COMPONENT}} from Nexus
  get_url:
    url: http://172.31.7.112:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /tmp/{{COMPONENT}}.zip
    username: admin
    password: admin123