
- name: update Cache
  apt:
    update_cache: yes
    
- name: download golang tar 
  get_url:
      url: https://golang.org/dl/go1.15.5.linux-amd64.tar.gz
      dest: /tmp
      
 
- name: Extract the Go tarball
  unarchive:
      src: /tmp/go1.15.5.linux-amd64.tar.gz
      dest: /usr/local
      remote_src: yes

- name: Import Download Nexus Artifacrs from Common role
  include_role:
    name: common
    tasks_from: download-nexus-Artifacts.yml




- name: Import Systemd Serive from Common role
  include_role:
    name: common
    tasks_from: setup-systemd.yml

# - name: Install Node Exporter Premetheus Monitoring from common role
#   include_role:
#       name: common
#       tasks_from: node_exporter.yml

# - name: Install Filebeat Monitoring
#   include_role:
#     name: common
#     tasks_from: filebeat
#   vars:
#     IS_STRUCTURED: true
#     LOG_FILES:
#       - { file: "/var/log/{{COMPONENT}}.log", type: "{{COMPONENT}}" }
      