- name: Install JAVA-8
  apt:
    name: openjdk-8-jdk-headless
    update_cache: yes
    state: present

- name: Install MAVEN
  apt:
    name: maven
    update_cache: yes
    state: present

- name: Import Download Nexus Artifacrs from Common role
  include_role:
    name: common
    tasks_from: download-nexus-Artifacts.yml


- name: Import Systemd Serive from Common role
  include_role:
    name: common
    tasks_from: setup-systemd.yml
